language: python
python:
    - 2.7
install:
    - pip install pep8
    - pip install coverage
    - pip install coveralls
    - python setup.py install
script:
    - coverage run --source=zaglushka setup.py test
after_success:
    coveralls
