language: python
python:
    - 2.7
install:
    - pip install pep8
    - pip install coverage
    - python setup.py install
script:
    - nosetests --with-coverage --cover-package=zaglushka --verbose zaglushka_tests/
